PACKAGE_NAME="new-lg4ff"
PACKAGE_VERSION="0.5.0"
MAKE[0]="make KVERSION=$kernelver"
CLEAN="make clean"
BUILT_MODULE_NAME[0]="hid-logitech-new"
BUILT_MODULE_LOCATION[0]="hid/"
DEST_MODULE_NAME[0]="hid-logitech"
DEST_MODULE_LOCATION[0]="/kernel/drivers/hid"
BUILT_MODULE_NAME[1]="ff-memless-next"
BUILT_MODULE_LOCATION[1]="input/"
DEST_MODULE_LOCATION[1]="/kernel/drivers/input"
AUTOINSTALL="yes"
